name: actualizar_oficial

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Python
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4
      - name: Actualizar
        run: |
          ./update_oficial.py
      - name: Commit
        run: |
          git config --global user.email "dolares-bot@example.com"
          git config --global user.name "dolares-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] update oficial"; git push -q "https://$GH_TOKEN@github.com/mauforonda/dolares.git" main)
